Add parameter "task_path" to method "input_files"
deepmodeling/fpop pull request #10
Opened 2023-03-29 01:31 UTC by Chengqian-Zhang

2023-03-29 03:17 UTC, wanghan-iapcm requested changes

2023-03-29 03:17 UTC, wanghan-iapcm commented on fpop/run_fp.py
> +    def input_files(self, task_path) -> List[str]:
please add UT for the method

2023-04-03 11:52 UTC, zjgemi approved these changes

2023-04-03 14:12 UTC, wanghan-iapcm approved these changes

2023-04-03 15:06 UTC, merged